#!/bin/sh
set -e

WEBUI_CONFIGJS="/opt/stackstorm/webui/config.js"
injecthdr="// Package injected:"

jsremove_flow() {
  [ -f "$WEBUI_CONFIGJS" ] || { echo "St2web \`${WEBUI_CONFIGJS}' not found"; exit 0; }
  perl -pi -0e "s#${injecthdr} flow-config(.|\n)*${injecthdr} flow-config\n##" $WEBUI_CONFIGJS
}

case "$1" in
    remove|upgrade)
      jsremove_flow
    ;;
    purge|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
